# Generated by Django 3.2.8 on 2021-10-10 21:14

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('test_app', 'User')
    Group = apps.get_model('test_app', 'Group')
    User(username="Userjkl334", group="group of slipknot").save()
    Group(name="group of slipknot", description= "group of slipknot description").save()


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(create_data),
   ]
